name: CI/CD for Initiate Payment API

on:
  push:
    paths:
      - 'initiate-payment/**'
  pull_request:
    paths:
      - 'initiate-payment/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: List files in initiate-payment directory
        run: |
          echo "Listing files in the initiate-payment directory:"
          ls -R initiate-payment
      

      - name: Build all modules
        run: mvn clean package -pl library,initiate-payment -am

      - name: Build Docker Image Locally
        run: |
          docker build -t initiate-payment:latest -f initiate-payment/Dockerfile .

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push-action@v5
        with:
          image: nd2k/initiate-payment
          tags: latest
          registry: docker.io
          dockerfile: initiate-payment/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
