name: CI/CD Pipeline for Faster Payment System

on:
  push:
    paths:
      - 'initiate-payment/**'
  pull_request:
    paths:
      - 'initiate-payment/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: '3.9.6'

      - name: Build all modules
        run: mvn clean package -pl library,initiate-payment -am
